Gtk/ButtonImages 0
Gtk/CursorThemeName "xcursor-plan9"
Gtk/CursorThemeSize 16
Gtk/FontName "Sans 10"
Gtk/MenuImages 0
Gtk/ToolbarStyle "Icons"
Net/EnableEventSounds 0
Net/EnableInputFeedbackSounds 0
Net/IconThemeName "Adwaita"
Net/ThemeName "Adwaita-dark"
Xft/Antialias 1
Xft/HintStyle "hintmedium"
Xft/Hinting 1
Xft/RGBA "rgb"
