# Theme & Icons
Net/ThemeName "my-xres-theme"
Net/IconThemeName "Adwaita"

# Cursors
Gtk/CursorThemeName "xcursor-plan9"
Gtk/CursorThemeSize 16

# Fonts & Rendering
Gtk/FontName "Sans 10"
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintmedium"
Xft/RGBA "rgb"

# Clean UI configurations for minimal WMs
Gtk/ToolbarStyle "Icons"
Gtk/ButtonImages 0
Gtk/MenuImages 0
Net/EnableEventSounds 0
Net/EnableInputFeedbackSounds 0
